### ISSUE TITLE
Staking Rewards Calculation via the App

### ISSUE THREAD

**Issue by B0ll3D3rF1ck3r** [PegasusPool/pegasus-tool-features#1]
Dear Pegasus Team, :-)

would it be possible to add a feature to the app, where one could define or type in their stake (real or hypothetical) in order to see how many ADA one has or would have received for staking each Epoch? (and the possibility to export that data to an Excel spreadsheet)

Of course taking into account all the known parameters like the tax, the saturation, the size of your stake compared to the rest of the staked ADA. 

I hope you guys understand what I mean. :-)

Thanks in advance for your great work.

Best, Daniel.

**Comment by PegasusPool** [comment]
Hi Daniel,

Thank you for raising the very first feature request :1st_place_medal: 

Surely you are familiar with the rewards calculator implemented by IOHK: https://staking.cardano.org/en/calculator/.

This tool is great and already has some of the functionality you are asking for here. 
We try not to reinvent the wheel, therefore we believe you should raise this request with the IOHK team to include rewards and balance projections via charts and excel sheets.

However, should you not get anywhere with IOHK and this is a feature desirable by other app users, we are happy to consider implementing this feature set.
We'll leave this issue open so others can indicate their interest in the features you propose here.

**Comment by B0ll3D3rF1ck3r** [comment]
Thanks for your reply, but the IOHK rewards calculator is not very valuable if you want to see your daily, weekly, monthly fluctuations of your personal rewards. Think of a graph just like tge ones in the app that would show you your rewards, maybe add a moving average, and one could see in one glimpse if ones rewards are steady, increasing or decreasing over time. 

That, you don’t have in the IOHK staking rewards calculator, you have to look at your app from an average user view, not so much from a stakepool operators view.

Best,

Daniel CIMA

**Comment by PegasusPool** [comment]
I am not planning to add a rewards calculator in the app.
It does have a rewards tracker though.
