### ISSUE TITLE
Relays marked down

### ISSUE THREAD

**Issue by genepool-one** [PegasusPool/pegasus-tool-features#10]
**Describe the bug**
I just had a question from someone that my relays were marked offline. I changed my relays just before mainnet went live so do you pull new registrations regularly to update relays. 

Pool - genePool one
Both new relays are up with approx 15 connections each and pingable
New relays are 
94.237.99.68
152.44.46.227

It just looks bad for us in your app having our relays marked offline :) thanks

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by PegasusPool** [comment]
Thank you for reaching out. I'm currently looking at improving relay discovery.
I'll update this issue as soon as it's done.

**Comment by PegasusPool** [comment]
This has now been fixed. Your pool is now showing 2 online relays in the app.

**Comment by genepool-one** [comment]
Great thanks for fixing that and providing the app for the community and looks like you are doing well on mainnet 🙌🏻
