### ISSUE TITLE
SMATE Stakepool ticker not showing

### ISSUE THREAD

**Issue by freewave2020** [PegasusPool/pegasus-tool-features#13]
**Describe the bug**
The pool I am delegated to is not showing the ticker. Stakemate, SMATE, pool ID dd31793ac6845d4fd63c4d4852414108c0661f494b76f48eb389e615

Is this a bug with this tool, or an issue with the pool? Many thanks

**Comment by PegasusPool** [comment]
Hi,

Thanks for reaching out. I checked the cardano-wallet logs, it is responsible for fetching your metadata and I found this:

```
Fetching metadata with hash 9271ebd2 from http://stakemate.io/poolMetaData.json
[cardano-wallet.pools-engine:Warning:123] [2020-09-26 16:14:48.17 UTC] Failed to fetch metadata with hash 9271ebd2: There's no known metadata for this pool.
```

Your metadata seems to be returning 404 when entered in a browser as well.

Is this the latest and correct metadata url for your pool?

**Comment by freewave2020** [comment]
Hi,

Thank you for your investigations, to be honest, i am not sure - the hash
of the stakepool is
dd31793ac6845d4fd63c4d4852414108c0661f494b76f48eb389e615 and I can see the
metadata for the stakepool in Deadalus and the stakepool on pooltool.io.

If I understand correctly, it looks like the stake pool metadata is not
correctly registered?

Thanks again,

Kevin

**Comment by PegasusPool** [comment]
Hi Kevin,

Your registered metadata url is still returning 404.
I'm closing this issue, but please reach out to the community on telegram for help if you need any: https://t.me/CardanoStakePoolWorkgroup
