### ISSUE TITLE
Changing pool on Daedalus does not reflect on app

### ISSUE THREAD

**Issue by TjaWic** [PegasusPool/pegasus-tool-features#19]
I switched pool on wallet but app still shows me the previous pool.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by PegasusPool** [comment]
Thanks for your feedback.
This is now fixed.
