### ISSUE TITLE
ROI calculation Mismatch

### ISSUE THREAD

**Issue by Oqulent** [PegasusPool/pegasus-tool-features#2]
**Describe the bug**
ROI calculation does not match anything that can be calculated from available data.

**To Reproduce**
Go to pooltool.io
click on SKY ticker--download reward history
calculate 14-day averages 
compare with Pegasus app
become confused. question life and  everything you know

**Expected behavior**
yay it's a match!

**Screenshots**
![image](https://user-images.githubusercontent.com/58947306/73541600-de63e980-4400-11ea-911b-e47b94eb8af0.png)

![pega](https://user-images.githubusercontent.com/58947306/73541825-6813b700-4401-11ea-808c-680d41a7d955.jpeg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by PegasusPool** [comment]
Pooltool tooltip:
![Screenshot from 2020-01-31 20-21-52](https://user-images.githubusercontent.com/58512297/73571872-7694b980-4467-11ea-80fd-f14f4f1be73d.png)

The reason for the difference is that pooltool calculates the ROI by compounding and it does not include pool fees paid to the pool.

On the other hand the Pegasus tool simply divides the rewards by the pool's effective stake, multiplies by 100 then 365 to get an estimated annual return on investment.

- It doesn't mean that one or the other tool is incorrect.
- These are estimated values, your ROI at the end of the year will not be what these tools show.
- Both tools can be used to compare pools' ROIs. If pool A has better ROI in the Pegasus tool than pool B, then pool A will also have a better ROI than pool B in pooltool. The values are estimates and for comparison only.

Thank you for raising, but we don't consider this a bug in the Pegasus app.

**Comment by Oqulent** [comment]
I don't think you understood the issue here. The question isn't about comparing your calculation to that of pooltoo.io. It is about looking at the raw data (it is in the blockchain), calculating averages (myself) but still not being able to produce yours. Can you show me your calculations? How did you arrive at your 12.2%?

**Comment by PegasusPool** [comment]
I understood what you are saying and I closed this because it's not an issue, but let me spell it out for you:

Example Epoch 48:

Pegasus App:
Effective Stake: 16m
Rewards for stakers: 7600
ROI = 7600 / 16m * 100 * 365 = 17.3%
![Screenshot from 2020-02-01 10-37-11](https://user-images.githubusercontent.com/58512297/73590819-d8443a80-44de-11ea-9f97-3757d3ed873c.png)

Pooltool:
Effective Stake: 16m
Rewards for stakers: 7600
ROI = *Some <strong>compounding</strong> ROI calculation* = 18.9%
Ask Papa Carp to give you his formula if you are interested.

As you can see the ROI for a single epoch is different on the two tools.
This means that the average will also be different. Doesn't mean that any of these are wrong, it's just a different approach to calculate ROI.
As I said before, it's just for comparing the pools on the same tool.

I didn't take adapools as a basis an I don't what their formula is to calculate ROI, but if you have a look at their website, the values for your pool's ROI is closer to what's on Pegasus. https://adapools.org/b628a5f5e987b03151c232b80d59a17e214e7105258c5bf8fc734a55ceb3e8d5

**Comment by Oqulent** [comment]
Here, let me try explaining differently:

1. Forget about pooltool.io for a second. 
2. take these numbers, which are from the blockchain.
3. do your ROI calculation, using the Pegasus formula (thanks for disclosing it btw)
4. see what you get for the 14-day period

A. I calculated the ROI, using these numbers from the chain. 
B. I used stakeholder rewards for each period and divided that by the amount of the stake.
C. I calculated three different versions since simple average didn't match that of Pegasus, but you can just ignore that and just focus on the simple average.

Finally I compared all the numbers with PEGASUS ROI. Upon discovering the discrepancies I let you guys know about the possible issue with screenshots of proof.

At the very least you can go through the steps and see it for yourself. For the last time, I am not comparing pooltool's ROI to that of PEGASUS. Attached is the excel file that spells it all out for you.

Hope you can find the bug and fix it. We all want Pegasus to succeed. It's a nice, convenient app and we all want to trust it. 

[skystats.xlsx](https://github.com/PegasusPool/pegasus-tool-features/files/4142646/skystats.xlsx)

**Comment by PegasusPool** [comment]
Here is the calculation for your pool:

epoch: 35 stake: 16303743 reward: 5934.0 roi: 13.284740810745117
epoch: 36 stake: 27149948 reward: 10177.0 roi: 13.68181257658394
epoch: 37 stake: 10620051 reward: 2090.0 roi: 7.18311051425271
epoch: 38 stake: 7258837 reward: 3116.0 roi: 15.668350177859072
epoch: 39 stake: 7718059 reward: 0.0 roi: 0.0
epoch: 40 stake: 5651260 reward: 2163.0 roi: 13.970247343070396
epoch: 41 stake: 5524740 reward: 0.0 roi: 0.0
epoch: 42 stake: 5029122 reward: 1059.0 roi: 7.685934045743969
epoch: 43 stake: 6719008 reward: 3989.0 roi: 21.669642304340165
epoch: 44 stake: 4419966 reward: 2061.0 roi: 17.019701056523964
epoch: 45 stake: 4387916 reward: 3257.0 roi: 27.09270186576042
epoch: 46 stake: 15992214 reward: 7494.0 roi: 17.104010739225977
epoch: 47 stake: 5488722 reward: 1001.0 roi: 6.656649762913844
epoch: 48 stake: 16029875 reward: 7602.0 roi: 17.309741966172535

AverageROI: 12.737617368799437

ROI is calculated for each epoch: reward/stake*100*365
Average is the sum of all 14 ROIs devided by 14

**Comment by Oqulent** [comment]
thanks for confirming my calculations. Now, we are getting somewhere.. 

Pegasus showed 12.2% for the exact same period. see the screenshot above. Where does the discrepancy come from?

**Comment by PegasusPool** [comment]
I told you already, but here it comes the 3rd time:
Epoch 34 has no rewards recorded for anyone in our database, so if you calculate the average ROI from epoch 33 to 46, the calculation will be off.
Probably this is what's confusing you.

We knew this when we released the app and was also aware that the calculation will have no issues once the average calculation is past epoch 34.

**Comment by Oqulent** [comment]
so your database is missing a whole epoch's worth of rewards. that wasn't clear. you did mention that epoch 34 had no rewards yes but that wasn't true so I thought you made that stuff up. 

ok so it is a data consistency issue on your side that should be resolved by now. thanks!

**Comment by PegasusPool** [comment]
Yes, like I said the first time to explain the difference on twitter... I don't make stuff up. I'm glad you now understand.

Anyway, thanks for checking.
