### ISSUE TITLE
Missing rewards from last fulfilled epochs 221 and 222. 223 just started.

### ISSUE THREAD

**Issue by AlwaysOn24** [PegasusPool/pegasus-tool-features#20]
**Describe the bug**

**To Reproduce**
1. Go to rewards
Only up to epoch 220 rewards are shown. 

**Expected behavior**

Rewards 221 and 222 should be shown. Because already 223 just startet an hour ago.

**Screenshots*

![Screenshot_2020-10-13-06-24-45-93_399fba12d46830238598f1d3704838c1](https://user-images.githubusercontent.com/58879146/95795434-e8bedd00-0d1c-11eb-8e31-93b92dcfeb03.jpg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by PegasusPool** [comment]
Hi there.
Thanks for reaching out.
Please check the app, the rewards for epoch 221 should be there already.
Please note, that rewards for epoch 222 are not distributed yet. This can be estimated and will be added soon to the app, but for now it only shows rewards that have actually be distributed to reward accounts.

Please feel free to reopen this issue if you have any more questions.
