### ISSUE TITLE
Display rewards with higher accuracy 

### ISSUE THREAD

**Issue by koromar** [PegasusPool/pegasus-tool-features#26]
**Is your feature request related to a problem? Please describe.**
A return of stake less than 1 ADA per epoch is displayed as 0 ADA. 

**Describe the solution you'd like**
Display rewards per epoch with double digit accuracy, e.g. ‘0.78’

**Describe alternatives you've considered**
Make accuracy configurable 

**Additional context**
People new to cardano with a low amount of ADA staked would welcome that change

**Comment by PegasusPool** [comment]
Hi @koromar 
Thank you for submitting a request.
This is now addressed and will be rolled out in the next release.

![device-2021-01-24-053910](https://user-images.githubusercontent.com/58512297/105622118-876fd500-5e06-11eb-9ed3-7763732c3c41.png)
