### ISSUE TITLE
Unable to add wallet

### ISSUE THREAD

**Issue by dud3man** [PegasusPool/pegasus-tool-features#27]
![7996C3F5-408B-4ABD-B880-E167A2A8BA98](https://user-images.githubusercontent.com/78951839/107743782-a9a1a680-6d65-11eb-8f5f-1344eb7d47af.png)
**Describe the bug**

**To Reproduce**
1. Go to '...'add wallet
2. Type name in
3. Use QR code from receive address on Daedalus wallet
4. Keeps loading and not loading wallet details

**Expected behavior**
I’m hoping to see details of the pool I’m delegating to but does not happen.
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone XS Max
 - OS: [e.g. iOS8.1] iOS 14.4

**Additional context**

**Comment by PegasusPool** [comment]
Hi there!
Thanks for reporting this.
There was a short period of time this morning when I was upgrading the backend that likely caused this issue.
I've just tested it and it worked. Please try again and feel free to reopen this issue if you still have difficulties adding your account.

All the best,
Pegasus
