### ISSUE TITLE
ROI Tracker Daily

### ISSUE THREAD

**Issue by TheHotTaco** [PegasusPool/pegasus-tool-features#3]
It would be great to have a breakdown of the daily ROI along with estimated rewards. 

Like tracking crypto, ideally you would select your pool, put in the delegated amount and then the algorithm figures out the rest and displays it in a pretty graph. Similar to coinstats.

For delegation tracking over X amount, you can charge for the app 😉 in ADA of course.

Ability to track multiple stakepools would be cool too 👍

**Comment by PegasusPool** [comment]
Hi @TheHotTaco,

Have you seen the new rewards tracking feature in the app?
You can scan your address from daedalus or yoroi and see the details of your rewards in the app. 
Would an additional ROI chart for you account be helpful and satisfy your request here?

**Comment by DFearing** [comment]
I'd love to see ROI on the rewards tab. Total and by Epoch would be awesome.

**Comment by PegasusPool** [comment]
Return on Stake for pools is now implemented in the app (broken down by epochs as well as lifetime ROS)
