### ISSUE TITLE
Reward for epoch 251 is different between app and web of pooltool.io.

### ISSUE THREAD

**Issue by siwas426** [PegasusPool/pegasus-tool-features#32]
***Describe bug**
1. (app) pools , search "YYG", click yyg, goto "Return on stake".
2. (WEB) home, search "YYG", click Action, goto "EPOCH", look at Delegator Reward of Epoch 251.

3. Reward of Epoch 251 in app is 0.00%, A0.
   in WEB it is 7.4k 
   WEB is correct.

***
App : iOS 
WEB: browser chrome

**Comment by PegasusPool** [comment]
This should now be resolved
