### ISSUE TITLE
Staking rewards decimals

### ISSUE THREAD

**Issue by spliff77** [PegasusPool/pegasus-tool-features#35]
**Is your feature request related to a problem? Please describe.**
It would help me a lot to see 3-4 more decimals in the rewards I get for staking. I manually input that in another app and I need it more precise if possible. 

**Describe the solution you'd like**
An option for decimals when seeing the rewards. 

**Describe alternatives you've considered**

**Additional context**
Thank you for looking at this

**Comment by PegasusPool** [comment]
We'll have an "export rewards" feature where the rewards will be shown with 6 decimals
