### ISSUE TITLE
Android rewards notification is using integers instead of float

### ISSUE THREAD

**Issue by raph2705** [PegasusPool/pegasus-tool-features#37]
**Describe the bug**
Android notification displays ₳0 for any reward < ₳1

**To Reproduce**

1. Stake ADA
2. Wait for rewards
3. Look at the notification

**Expected behavior**
A float value with at least 2 decimals is expected here.

**Screenshots**
![Screenshot_20210501_164255](https://user-images.githubusercontent.com/72207390/116822029-fcc51180-ab7c-11eb-97ea-88fe15c1df7c.jpg)

**Smartphone (please complete the following information):**
 - Device: Huawei P30
 - OS: Android 10
 - PoolTool apk version 3.11.0

**Additional context**
n/a

**Comment by PegasusPool** [comment]
This should now be resolved
