### ISSUE TITLE
Rewards total not updating on ios

### ISSUE THREAD

**Issue by maximilianotaverna** [PegasusPool/pegasus-tool-features#39]
iphone 12mini
iOS 14.5.1
pooltool version 3.11

alert for new staking rewards notification alerts to new reward for this epoch with correct amount. However in app total rewards for 2 wallets does not update to reflect new total calculation. 

restart ios 
restart app 
reinstall app 

all fail to fix problem

**Comment by PegasusPool** [comment]
This should now be resolved. Feel free to reopen if it's not the case
