### ISSUE TITLE
iOS - Favourites page/list data refresh

### ISSUE THREAD

**Issue by lunarpool** [PegasusPool/pegasus-tool-features#4]
**Is your feature request related to a problem? Please describe.**
I'm intuitively trying to refresh the stats on Favourites page by drag down tap, but it does nothing. Closing the app and running again made a refresh for me.

**Describe the solution you'd like**
Show loading icon so it is clear it is doing something and refresh the stats in the list.

**Describe alternatives you've considered**
No need to dragging down, but a regular data check on background when used/watching the list.

**Additional context**
I have seen that just once because the data are not changing so often so maybe it was just a coincidence or something wrong with my phone or app sleeping/freezing

**Comment by PegasusPool** [comment]
Thank you for the suggestion @lunarpool 
We'll look into implementing either the proposal or the alternative in a future release.

**Comment by PegasusPool** [comment]
The favorite pools are refreshed every time users navigate to that tab, or back from the pool details screen. The app doesn't use pull to refresh anywhere and a live update is preferred when needed (just like you see it on the explorer screen).
