### ISSUE TITLE
Current epoch not showing on dashboard

### ISSUE THREAD

**Issue by sedwardstx** [PegasusPool/pegasus-tool-features#44]
**Describe the bug**
Details for current epoch not showing on dashboard.  Currently many hours later at 12% into epoch 281 and dashboard graphs still showing up to 280 only.  Estimated rewards for 281 not shown either.

**To Reproduce**
1. wait for end of epoch
2. Click on 'Dashboard'
3. details do not get updated after new epoch starts
4. wait for hours, still not updated

**Expected behavior**

1. wait for end of epoch
2. Click on 'Dashboard'
3. details get updated after new epoch starts
4. or wait for short amount of time < 1 hr to see next epoch details

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: v10
 - Browser your app, chrome
 - Version latest

**Additional context**

**Comment by PegasusPool** [comment]
Thanks for reporting.
Sometimes it takes hours after the epoch switch for the rewards and graphs to be updated.
We're working on optimising the epoch switch so the data is available for users as fast as possible.
