### ISSUE TITLE
‘Delegated to’ nav leads to grey screen

### ISSUE THREAD

**Issue by ryanhalley** [PegasusPool/pegasus-tool-features#45]
**Describe the bug**
In the iOS app, on the first tab I click ‘Delegated To’ and the nav takes me to (presumably) the staked pool page for a split second, then the entire screen changes to solid grey.
**To Reproduce**
1. Go to first tab
2. Scroll down and click on 'Delegated To’ (I am using SPIRE)
3. Light grey screen appears, no text.
4. Quit app, reopen, retry, same thing.

**Expected behavior**
Presumably, the nav should link to the pool details. If I go to the 4th tab (if I recall), I can get to pool details.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone7Plus
 - OS: iOS14.7.1
 - Browser Safari
 - Version

**Additional context**

**Comment by mitranos** [comment]
Happening as well on my iPhone 12 Pro after I have sent the delegation money to PoolTool

**Comment by PegasusPool** [comment]
This should now be resolved
