### ISSUE TITLE
iPhone bottom navbar is cut

### ISSUE THREAD

**Issue by mitranos** [PegasusPool/pegasus-tool-features#47]
**Describe the bug**

**To Reproduce**
1. Have an iPhone X, 11, 12 

**Expected behavior**
The bottom navbar should not be cut

**Screenshots**
Added screenshots.

![240AE9B9-D33D-4EDF-A218-C30ABD5BA8B1](https://user-images.githubusercontent.com/9023453/131241356-2c94bc8c-87ea-4f54-8a3e-d650746f1b72.png)

**Desktop (please complete the following information):**
 - OS: latest
 - Version latest

**Smartphone (please complete the following information):**
 - iPhone 12

**Additional context**
This is happening in the .

**Comment by PegasusPool** [comment]
Thanks for reporting this.
This is due to the form factor of your device and there isn't much we can do about this minor issue.
