### ISSUE TITLE
Android app crash

### ISSUE THREAD

**Issue by glezster** [PegasusPool/pegasus-tool-features#48]
**Describe the bug**
Android app gets a white screen and a crash when tapping "Delegated to" button for any account in dashboard.

**To Reproduce**
1. Go to 'Dashboard'
2. Click on 'Delegated to'
3. See error

**Expected behavior**
Go to a pool info page

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Android 11

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi10TPro
 - OS: Android 11 MIUI 12.5.3

**Additional context**
It happens with verified and not verified accounts

**Comment by PegasusPool** [comment]
This should now be resolved
