### ISSUE TITLE
Incorrect number of blocks

### ISSUE THREAD

**Issue by lunarpool** [PegasusPool/pegasus-tool-features#5]
**Describe the bug**
Hi PegasusPool,

wanted to contact you on Twitter and Telegram, but cannot send you direct message so wanted to use this form instead of public tweet.

Out pool MOON9 shows currently 77% performance despite created all the blocks from all the slots assigned for last 4 days. Why is that? According to Shelley Explorer our pool created 200 blocks, your tool shows just 199.

Could you please correct your stats? Many thanks

Dusan
lunarpool.io

**To Reproduce**
Simply check total number of blocks with official Shelley Explorer

**Expected behavior**
To be in sync with blockchain

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: iOS

**Additional context**

**Comment by PegasusPool** [comment]
Hi,

Performance:

POOL9's current performance is 96% with 6 blocks created in the epoch.
The value is coming from the cardano-wallet app developed by IOHK.
It is calculated by estimating the number of blocks a pools should create given its effective stake and applies a function on that and the actual blocks created and epoch progress. Unfortunately (and IOHK does not explain this anywhere) if a pool was unlucky in the leader election for an epoch and they got assigned less slots than is normally expected for its stake, the performance can be less than 100% even if no blocks were missed and all was created successfully. This also happened with the Pegasus pool several times. Unfortunately IOHK needs to improve this calculation, until that is done we can do nothing regarding this. Some pools will be lucky for a few epochs and unlucky in others.


Total number of blocks:

Both the Pegasus app and the shelley explorer show 202 total blocks. 
However they can get temporarily out of sync for the following reasons:
- one or the other node is on a fork or the node is stuck (this is rarely the case in the Pegasus app, but we've seen the shelley explorer struggling in the past)
- The total number of block created are updated in the app every 10 minutes. It might be the case that the shelley explorer updated the total count, but the app not yet.
