### ISSUE TITLE
All says pool is retiring it’s wrong 

### ISSUE THREAD

**Issue by jbarros35** [PegasusPool/pegasus-tool-features#51]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

This is very simple. My pool was set to retire but I change my mind submit another certified to Cardano and pool won’t retire. Now you display my pool will retire and hurt my delegations possibilities! Please fix that

**Comment by PegasusPool** [comment]
Next time mention which pool you are talking about.
It's fixed now by the way.
