### ISSUE TITLE
pool is hidden

### ISSUE THREAD

**Issue by xptodevx** [PegasusPool/pegasus-tool-features#52]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
This is very simple your tool completely hides my pool that is named CHEFF registered in February in your list.
![C6C9BE70-A43F-400A-888E-4ECCE81278B3](https://user-images.githubusercontent.com/87699618/141758372-41510723-d466-413a-95d1-54ba739a3c36.png)

**Comment by PegasusPool** [comment]
I demand you tell me your poolid!

**Comment by PegasusPool** [comment]
Fixed
