### ISSUE TITLE
all time average returns plus date scale on top

### ISSUE THREAD

**Issue by B0ll3D3rF1ck3r** [PegasusPool/pegasus-tool-features#6]
Hi there, 

> would it kindly be possible to add a scale on top of the rewards chart with the dates? Calendar days, and month. Not just the Epochs.

> would it kindly be possible to add an all time average that actually shows the value?

Like this one can make calculations more easily, knowing how much they made on average while staking ADA.

**Comment by PegasusPool** [comment]
Thank you for reaching.
Rewards tracking is not available on mainnet at the moment.
I will keep this in mind should this feature be back in the future.
Closing this issure for now.
