### ISSUE TITLE
New icon after selecting a pool

### ISSUE THREAD

**Issue by KingStake21** [PegasusPool/pegasus-tool-features#7]
After selecting a pool you are taken to the pool info page. In the bottom right there is an icon to set as a favorite. Since all the tabs (buttons) are on the bottom no matter what page your looking at would it be possible to add a back icon on the bottom as well once you viewing a pool? The back button is on the top left but since this is a mobile app users thumbs are usually on the bottom of the screen anyways so a simple back icon on the bottom would be nice.

**Comment by PegasusPool** [comment]
Thanks for reaching out.
Placing back buttons on the bottom of a screen is not something mobile users expect and therefore this will not be implemented.
