### ISSUE TITLE
Improve pool searching capability

### ISSUE THREAD

**Issue by bergr01** [PegasusPool/pegasus-tool-features#8]
Hi

This issue mostly affects pools that have ticker symbols that consist of A-F letters and numbers.

E.g. if i type aaa into the search field in Pegasus Tool, my AAA pool isn't even shown on the first page of results currently because as a part of the search multiple data fields are consulted for substring matches, including Pool ID (GUID). 

Ideally ticker symbols would be used as a first priority matching, with the pool IDs being distant last (one easy way of deciding whether to look in Pool ID field is to check the length of the search field string - if user is searching by pool iD most likely they would have copy pasted a rather long string from elsewhere)

This would allow people quick and easy way to find the pool they are looking for

**Comment by PegasusPool** [comment]
Thanks for raising the issue.
This is now fixed and will be included in a future version (2.4.0)
