### ISSUE TITLE
Unchecking Hide Saturated Pools not working

### ISSUE THREAD

**Issue by JSCSJSCS** [PegasusPool/pegasus-tool-features#9]
**Describe the bug**
After checking box to hide saturated pools, those seemed to be hidden, but after unchecking the option, they do not come back into views.

**To Reproduce**
1. Go to options, select hide saturated pools
2. See those pools disappear from searches
3. Uncheck that option.
4. Those pools do not return to view.

**Expected behavior**
Expected to see all pools again after clearing hide saturated pools option.

**Smartphone (please complete the following information):**
 - Device: Moto G5
 - OS: Android 8.1.0

**Comment by PegasusPool** [comment]
Thanks for reporting.
This is a known issue at the moment as cardano-wallet does not provide correct saturation levels for pools so the saturation filter does not work essentially. I will keep this issue up until resolved by a cardano-wallet update.

**Comment by PegasusPool** [comment]
This has now been fixed.
